### ISSUE TITLE
Fails on JDK 11 due to dependency on removed Java EE API

### ISSUE THREAD

**Issue by bjhargrave** [de-jcup/egradle#355]
When running Eclipse (2018-09) on JDK 11, the javax.xml.bind package is no longer present in the JRE. So egradle fails when opening an edit window.

`Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException cannot be found by de.jcup.egradle.eclipse.plugin.main_2.5.0`

So I think you either need to remove dependencies in the Java EE APIs removed in JDK 11, or your feature needs to make sure a plugin which exports the desired packages is available.

**Comment by de-jcup** [comment]
@bjhargrave Thank you for reporting this! I will fix this in next time.

**Comment by theit** [comment]
I fixed this by doing the following steps:
1) Installed the XML Binding for Java 2.2.0.v201105210648 from Eclipse Orbit repository (http://download.eclipse.org/tools/orbit/downloads/drops/R20180905201904/repository)
2) Uninstalled the former installed EGrade IDE 2.5
2) Openend the de.jcup.egradle.eclipse.plugin.main_2.5.0.jar from ~/.p2/pool/plugins
3) Added " javax.xml.bind" to the META-INF/MANIFEST.MF file to "Require-Bundle:" entry
4) Reinstalled EGradle IDE
Now the editor works again under JDK 11 without showing an error when I open a Groovy file :-)

**Comment by de-jcup** [comment]
Thank you for your local workaround and the description.
I will download the JDK 11 on my linux machine and try to fix the problem by either adding dom4j lib, or xml binding jar or references the orbit parts as you have done. 

PS: When I created the xml reading code I thought "Oh I should use the internal JDK XML implementation instead of adding another dependency - e.g. dom4j - because its always available..." OMG ...

**Comment by de-jcup** [comment]
Having https://github.com/de-jcup/egradle/issues/359 issues with Linux and GTK before merging I will try out with windows

**Comment by realwuffi** [comment]
Hi all,
any updates in this issue? It's still the same problem in 2019-03.
The javax.xml.bind_2.2.0.v201105210648.jar is shipped with eclipse, but I can't get the Editor running, even with the fix from @theit.
I could not find the jar in the user home but in the eclipse/plugins directory.
I'm running Eclipse with Adopt OpenJDK 11.0.2

Any help appreciated!
Wolfgang

**Comment by de-jcup** [comment]
@realwuffi I release egradle 2.6.0 on marketplace which contains the fix. Should now work with JDK11 without problems

**Comment by realwuffi** [comment]
Thanks, runs without any problems so far!
